### ISSUE TITLE
Again 'http.server'  not found

### ISSUE THREAD

**Issue by anurag3301** [p00f/cphelper.nvim#10]
![image](https://user-images.githubusercontent.com/52702259/127841620-31eca1bf-0d03-4a90-a91e-cf249bb5a940.png)

### I have already installed `lua51` on my arch and ran following
```sh
sudo luarocks install http --lua-version 5.1
sudo luarocks install http
```
### Here you can see, no error
![image](https://user-images.githubusercontent.com/52702259/127842238-7216b9cf-9751-485d-8604-585cffe4eff7.png)

![image](https://user-images.githubusercontent.com/52702259/127842113-45f7ec3f-0056-4cde-8a50-fc40a9d92d7d.png)

### `:version` from nvim
![image](https://user-images.githubusercontent.com/52702259/127842550-ddbfac68-eb4f-4052-b0bb-753a9a5fe5f1.png)

**Comment by anurag3301** [comment]
### Output of `luarocks list`
![image](https://user-images.githubusercontent.com/52702259/127843911-8d7bc862-a53b-47b3-84a0-a9e587953103.png)

**Comment by p00f** [comment]
Luajit 2.1 is based on lua 5.2 i think. But yiu dont need to do this if you use packer.nvim

**Comment by p00f** [comment]
Huh the error says it is searching for the module in lua 5.1, why doesnt it work

**Comment by anurag3301** [comment]
Done installed `lua52` and http with version 5.2. and the repl doesn't give any error
![image](https://user-images.githubusercontent.com/52702259/127844429-2e170b59-63d0-4de9-a66c-660282ea88ef.png)

**Comment by anurag3301** [comment]
> Huh the error says it is searching for the module in lua 5.1, why doesnt it work

Maybe this is a PATH issue. I have given output of `luarocks list`

**Comment by anurag3301** [comment]
You can see in the error output. None of them mentioned `/usr/lib/luarocks` or `/home/anurag/.luarocks`

**Comment by anurag3301** [comment]
output of `luarocks list  --lua-version 5.1`
![image](https://user-images.githubusercontent.com/52702259/127845832-1a8807dd-57a3-46ed-90c3-ea6b6569a564.png)

**Comment by p00f** [comment]
You use packer.nvim right?

**Comment by anurag3301** [comment]
yeppp, you can check my config if you want, [github](https://github.com/anurag3301/my-linux-setup/tree/main/config/nvim)

**Comment by p00f** [comment]
You don't need to manually install anything then, the line is all you need

https://github.com/anurag3301/my-linux-setup/blob/b866d5ac04b1e98c296fbdf385567d4d7b11fe72/config/nvim/lua/plugins.lua#L4

**Comment by anurag3301** [comment]
I removed that line, Ran `PackerUpdate`. but no change

**Comment by anurag3301** [comment]
Can I do a hacky fix, like taking the lib files and placing them where it is expecting them.

**Comment by p00f** [comment]
You can try I guess? Like nothing can go wrong if you place them in the `/home/anurag/...` locations

![image](https://user-images.githubusercontent.com/36493671/127850356-e7c951a5-07c3-448c-8710-15fa95cce893.png)

**Comment by anurag3301** [comment]
### Oh man, finally it's working. This hacky fix worked.
Tho for anyone in future face the same, this is what I did
All the lib files installed by luarock was stored in this path: `/usr/share/lua/5.1`
But nvim's lua was looking for those lib files in the above-mentioned paths.
So I just picked on and placed all my lib files there.
I chose `/usr/local/share/lua/5.1`.
Just run 
```sh
sudo mkdir -p /usr/local/share/lua/5.1
sudo cp /usr/share/lua/5.1/*  /usr/local/share/lua/5.1/
```
But it was not done yet, It needed some more lib files like `_cqueues.so` and `lpeg.so`.
And these lib files were stored in `/usr/lib/lua/5.1`
So I just ran 
```sh
sudo cp /usr/lib/lua/5.1/*   /usr/local/share/lua/5.1/
```
Now everything is working.

**Comment by p00f** [comment]
Arch users can install [`lua51-http`](https://archlinux.org/packages/community/any/lua51-http/)

**Comment by p00f** [comment]
I'll do it when https://github.com/neovim/neovim/pull/14871 is merged
