### ISSUE TITLE
Unable to Test the code

### ISSUE THREAD

**Issue by proro485** [p00f/cphelper.nvim#11]
:CphTest command is not working and giving the following error.

![Issue1](https://user-images.githubusercontent.com/72189840/127883243-fb69188a-1b02-4782-9d65-b4cad62f6d0e.png)

**Comment by p00f** [comment]
Do `:lcd %:p:h` and then test (this changes neovim's working directory to match the current file)

**Comment by proro485** [comment]
Thanks, it is working now. Do I have to do this everytime or was it just a one off?

**Comment by p00f** [comment]
It should not happen normally. If it happens again I'll reopen the issue

**Comment by anurag3301** [comment]
Hey @proro485, there is an alternative automatic way which I use, you can try also. make the following change in packer config and install 'ygm2/rooter.nvim' along with cphelper
```lua
    use {
      'p00f/cphelper.nvim',
      requires = {
        'nvim-lua/plenary.nvim',
        'ygm2/rooter.nvim',
        opt = true
      }
    }
```

Now just add the following in the init.lua or anywhere else
```lua
-- Rooter config
vim.g.rooter_pattern = { 'input1', 'output1' }
```
If it detected the file `input1` or `output1`, it will automatically cd into it. Hope it helps :)
