### ISSUE TITLE
Add a command to stop the server

### ISSUE THREAD

**Issue by crookshanks003** [p00f/cphelper.nvim#12]
I mistakenly selected :CphReceive but I dont want to add new problem. So now my vim is stuck in :CphReceive. How do I stop it. esc, C-c does not work.

**Comment by p00f** [comment]
You can quit neovim of close the terminal window. Any unsaved changes to files are normally saved to a swapfile and you'll be able to recover them when you edit the same file again.

I'll add a `CphStop` command some time

11-Aug-2021 09:31:16 Pritesh ***@***.***>:

**Comment by p00f** [comment]
`:CphReceive` is no longer blocking (you can use the command line after running `:CphReceive`). Closing neovim now closes the server because it is tied to neovim. I've also added a CphStop command but I'm not sure if it works, because the callback I give it never runs
