### ISSUE TITLE
Special character in path messes-up nvim

### ISSUE THREAD

**Issue by anurag3301** [p00f/cphelper.nvim#13]
So the Cphelper directly creates the directory with the name of the problem. Well it cause some problem when the name of the problem contains some special character or eg this codefroces problem name
> I_love_%username%

Problem link: [codeforces](https://codeforces.com/problemset/problem/155/A)

You get this error when you try to open the solution file
![image](https://user-images.githubusercontent.com/52702259/130201293-9fbb939b-cf01-4be4-9696-0db0b8597880.png)

pwd `/home/anurag/problems/Codeforces/CodeforcesRound109(Div2)/AI_love_%username%`

I don't know the severity of this issue or how often this is, Just wanted to inform you.
You can try it yourself. 
😇

**Comment by p00f** [comment]
can you try out the `#13` branch? I dont have my computer rn

**Comment by p00f** [comment]
Fixed by #14
