### ISSUE TITLE
Get the link of the problem and write to the solution.cpp

### ISSUE THREAD

**Issue by anurag3301** [p00f/cphelper.nvim#18]
Hey Is there a way to get the link of the problem and write that link in the solution.cpp created by the plugin like you can see at the first line of the following code.
```cpp
// https://codeforces.com/problemset/problem/139/A
#include<bits/stdc++.h>
using namespace std;

int main(){
  int n, x; cin >> n;
  vector<int> week;

  for(int i=0; i<7; i++){
    cin >> x;
    week.push_back(x);
  }
  while(1){
    x = 1;
    for(int i:week){
      n-=i;
      if(n<=0){
        cout << x << endl;
        return 0;
      }
      x++;
    }
  }
}
```

Does the `Competitive Companion` Extension also provide the problem link which can be written using this cphelper.
If it is possible how can I achieve this, possibly in my fork.

**Comment by p00f** [comment]
Added `g:cph_url_register`, see the readme.

**Comment by piush-terminalwitchcraft** [comment]
and timestamp? when the problem is created?

**Comment by p00f** [comment]
Use some snippet tool to add the current time
