### ISSUE TITLE
No write since last change (add ! to override)

### ISSUE THREAD

**Issue by KoushikSahu** [p00f/cphelper.nvim#19]
**Description:**

I have been getting the following error once in a while when I have parsed the problem and left the file in insert mode before continuing to write into the file again.

**Error message:**

```
Error executing vim.schedule lua callback: ...nfig/nvim/plugged/cphelper.nvim/lua/cphelper/prepare.lua:62: Vim(edit):E37: No write since last change (add ! to override)
stack traceback:
[C]: in function 'cmd'
...nfig/nvim/plugged/cphelper.nvim/lua/cphelper/prepare.lua:62: in function 'prepare_files'
...nfig/nvim/plugged/cphelper.nvim/lua/cphelper/receive.lua:36: in function <...nfig/nvim/plugged/cphelper.nvim/lua/cphelper/receive.lua:30>
```

**Steps to reproduce:**

There is no such particular pattern I found to reproduce this error. Normally I get this error when I leave the file in insert mode and then try to write and save it into the file again.

**Comment by p00f** [comment]
Does this still happen? If yes, can you post the new error message? The line numbers might have changed

**Comment by p00f** [comment]
Closing due to no response from author
