### ISSUE TITLE
cpp template for solution.cpp

### ISSUE THREAD

**Issue by anurag3301** [p00f/cphelper.nvim#24]
Hey I wanted to create a template for solution.cpp and inject the following code.
This is whats inside `~/.config/nvim/templates/cptemp.cpp`
```cpp

#include<bits/stdc++.h>
#define FOR(n) for(int i=0; i<n; i++)

using namespace std;

int main(){

}
```
I followed online guide and added following in my nvim config
```lua
vim.cmd("autocmd BufNewFile solution.cpp 0r ~/.config/nvim/templates/cptemp.cpp")
```
If I create a file with `nivm solution.cpp` its working but in cphelper it isn't. Cphelper is still creating blank solution.cpp.

If I am doing something wrong, How can I fix it. :)

**Comment by p00f** [comment]
the event should be bufread, not bufnewfile (because the file has already been created)

**Comment by anurag3301** [comment]
It works fine when the file is created after `:CphReceive`, but it add the code to any time I open an existing `solution.cpp`
![image](https://user-images.githubusercontent.com/52702259/164873415-9edc60cc-9b91-4de9-bd4c-688080ad11cd.png)

As I can understand its `autocmd BufRead` It will trigger every time I read the file.

**Comment by p00f** [comment]
ah right, should be fixed now

btw you can just use snippets instead of workarounds like these - which are also useful for other standard procedures

**Comment by anurag3301** [comment]
Yeah, I'll look for snippet way. But it would be really great if we have an option to inject a custom boilerplate code for the `solution.cpp`. A lot of people have their own boilerplate code specifically for competitive programming. I think It can be done when cphelper creates the solution.cpp file

**Comment by p00f** [comment]
then put your boilerplate in a snippet - it'll even place your cursor in the right position when you select it
```cpp

#include<bits/stdc++.h>
#define FOR(n) for(int i=0; i<n; i++)

using namespace std;

int main(){
    int t; cin >> t;
    while(t--) {
        // CURSOR HERE
    }
}
```
