### ISSUE TITLE
Solution marked wrong until whitespace is removed

### ISSUE THREAD

**Issue by pavanscoding** [p00f/cphelper.nvim#25]
The plugin marks the solution wrong until the whitespace is removed. However, it does give a warning about the whitespace. While it isn't too bad of an issue, it is slightly a bit of a pain.

**Comment by p00f** [comment]
Some judges don't accept extra whitespace. To be on the safer side, it is better to consider such solutions wrong

**Comment by pavanscoding** [comment]
> Some judges don't accept extra whitespace. To be on the safer side, it is better to consider such solutions wrong

Is it possible to differentiate between different checkers?

**Comment by p00f** [comment]
Nope, too much work
