### ISSUE TITLE
Error while parsing through problem

### ISSUE THREAD

**Issue by pavanscoding** [p00f/cphelper.nvim#27]
I was using the plugin to parse through the following problem, however, I received an error. 
```
Error executing vim.schedule lua callback: ....local/share/nvim/cphelper.nvim/lua/cphelper/prepare.lua:24: attempt to perform arithmetic on local 'sep_pos'
(a nil value)
stack traceback:
        ....local/share/nvim/cphelper.nvim/lua/cphelper/prepare.lua:24: in function 'prepare_folders'
        ....local/share/nvim/cphelper.nvim/lua/cphelper/receive.lua:32: in function <....local/share/nvim/cphelper.nvim/lua/cphelper/receive.lua:27>
```
Here is the problem.
https://dmoj.ca/problem/pickit

I think the reason that there is an error is that the problem is not from a contest, so the plugin doesn't know how to create the folders.

**Comment by p00f** [comment]
Thanks, this is now fixed

**Comment by pavanscoding** [comment]
The same thing happened here for this problem:
https://judge.yosupo.jp/problem/staticrmq

I'm pretty sure for the same reason as well.

**Comment by p00f** [comment]
Thanks, this is also fixed
