### ISSUE TITLE
Support custom compilation options

### ISSUE THREAD

**Issue by clatisus** [p00f/cphelper.nvim#28]
Hi, I find it's very useful to add global variables for adding custom compilation options (e.g `--std=c++17`), how do you think?

If we agree it's a valid use case, I can compose a PR.

**Comment by p00f** [comment]
https://github.com/p00f/cphelper.nvim/blob/27f19bb5defc68200aa1894a78e814453d8136b9/doc/cphelper.txt#L74-L78

Are you thinking of something else?

**Comment by clatisus** [comment]
sorry didn't notice this one, it's exactly what I want! Thank you
