### ISSUE TITLE
Folds in Case output in cphtest

### ISSUE THREAD

**Issue by anurag3301** [p00f/cphelper.nvim#30]
Hey, is there a change in the plugin which makes the output of testcases in CphTest folded like this

![image](https://user-images.githubusercontent.com/52702259/210392472-981a2ebd-5164-4a99-889d-abb8c3e5d1c4.png)

Or there is something wrong with my overall nvim configuration
My nvim configuration if you wanna have a look https://github.com/anurag3301/my-linux-setup/tree/main/config/nvim

And is there a change in the configuration style of this plugin because this doesn't seem to be working
```lua
-- CpHelper config
vim.g.cphdir = os.getenv( 'HOME' )..'/problems'
```

**Comment by p00f** [comment]
For folds you just go to the line after `Case #XXX` ie `Input:` and press `zc`

Regarding the latter, yes there is a change in the config: https://github.com/p00f/cphelper.nvim/commit/c873e28fa743324bb949ef0f33eeaf49d059af08

**Comment by anurag3301** [comment]
Is it possible to not make it fold like it was previously?

**Comment by anurag3301** [comment]
And regarding the change, can you please tell me a simple syntax to write the configuration for the following, I am not very familiar with lua syntax
```lua
vim.g.cphdir = os.getenv( 'HOME' )..'/problems'
```

**Comment by p00f** [comment]
1. `autocmd FileType Results setlocal foldlevel=5`
2. change `vim.g.cphdir` to `vim.g["cph#dir"]`

**Comment by anurag3301** [comment]
Perfect, thank you :), closing the issue.
