### ISSUE TITLE
Windows like xeluxee/competitest.nvim

### ISSUE THREAD

**Issue by vishalpaudel** [p00f/cphelper.nvim#31]
The competitest project is a great one(especially the aesthetics of the window management. But, it lacks the beautiful folder sturucture of cphelper.nvim!

I was hoping if we could modify the cphelper test-cases windows a little bit? (taking inspiration from competitest.

-Vishal

**Comment by p00f** [comment]
I like the current simple ui, I think you'd have more luck asking xeluxee to add folders

**Comment by vishalpaudel** [comment]
[I have asked xeluxee here](https://github.com/xeluxee/competitest.nvim/issues/32).

Yes, thanks for replying, I agree, I think the simple UI is nice enough.
