### ISSUE TITLE
How to solve this Issue

### ISSUE THREAD

**Issue by Dimpal-Kalita** [p00f/cphelper.nvim#32]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/3ac453a3-8efe-4696-a6cd-121ed900f6ac)

I am Facing this while running **CphTest**

**Comment by p00f** [comment]
Which language are you using?

What happens if you add `vim.print("CMD = ", cmd)` just before https://github.com/p00f/cphelper.nvim/blob/ab259315496514d58b2021048ef40437ad0f5814/lua/cphelper/run_test.lua#L83?

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/79be83d9-9ba2-46e5-b23f-fc37a36a4043)

I am Using C++, Build: 
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/ccedbd5b-118c-4813-bb71-d0f52b17c317)

**Comment by p00f** [comment]
That screenshot shows it's working though? When does this happen

**Comment by Dimpal-Kalita** [comment]
Yes, It is Working .. But whenever I run **CphTest** it shows time out and no output.

And How do I change the directory from C to D
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/ef498513-ab6c-4c71-8ac8-f7273dad4b53)
It is not Working

**Comment by p00f** [comment]
> What happens if you add `vim.print("CMD = ", cmd)` just before
> 
> https://github.com/p00f/cphelper.nvim/blob/ab259315496514d58b2021048ef40437ad0f5814/lua/cphelper/run_test.lua#L83
> ?

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/3af9c251-7f99-488f-92da-6407d0387fe1)
It shows this

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/04453e0c-e700-44e7-8b12-9af8ffba3c51)
Command line is showing this now

**Comment by p00f** [comment]
Use `:messages` to get the full output

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/c6b45577-031f-42fd-bd29-37cf2f861345)

**Comment by p00f** [comment]
can you change vim.print to just print

**Comment by p00f** [comment]
Can you try changing the slash to a backslash?

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/f9c72c4c-9dbb-464c-ba75-9fcc595e38d4)

it didn't work

**Comment by p00f** [comment]
I'll need some more time to investigate this as I don't use Windows - you can try to find the problem in this function:

https://github.com/nvim-lua/plenary.nvim/blob/499e0743cf5e8075cd32af68baa3946a1c76adf1/lua/plenary/path.lua#L464

**Comment by p00f** [comment]
It's this issue: https://github.com/nvim-lua/plenary.nvim/issues/456 - this bug only happens on windows

**Comment by p00f** [comment]
What is printed if you add `print(problem_dir)` just before this line?

 https://github.com/p00f/cphelper.nvim/blob/ab259315496514d58b2021048ef40437ad0f5814/lua/cphelper/prepare.lua#L30

**Comment by Dimpal-Kalita** [comment]
![image](https://github.com/p00f/cphelper.nvim/assets/97835980/55495468-4209-4a2c-a1cc-5ef9f946d600)

I did this and Printed it as you said.. and it worked... It parsed the proble in correcrt Directory.

Thank you for Replying and Solving the issue
