### ISSUE TITLE
Automatic unfolding of test cases window on `:CphTest`

### ISSUE THREAD

**Issue by haxfn** [p00f/cphelper.nvim#34]
The extra `zR` is annoying, is there a work around so that the input and output window auto unfolds?

**Comment by p00f** [comment]
You need to increase your `foldlevelstart` - if you don't want to change the global option you can
`autocmd FileType Results setlocal foldlevel=5`

https://neovim.io/doc/user/options.html#'foldlevel'
https://neovim.io/doc/user/options.html#'foldlevelstart'
