### ISSUE TITLE
Nothing happens when run CphReceive

### ISSUE THREAD

**Issue by laniakeaaa** [p00f/cphelper.nvim#5]
![github](https://user-images.githubusercontent.com/61778648/114605555-41126f80-9cab-11eb-9641-bfbec78b8ec6.png)

**Comment by laniakeaaa** [comment]
I press competitive companion icon, but again nothing happens.

**Comment by p00f** [comment]
Can you paste the output of `:version` here?

**Comment by p00f** [comment]
@laniakeaaa can you please paste the output of `:version` here?

**Comment by p00f** [comment]
Probable fix is `sudo luarocks remove http` then `sudo luarocks install http --lua-version 5.1`

**Comment by p00f** [comment]
(You need to have lua 5.1 installed to do this)

**Comment by p00f** [comment]
I'll change the readme

**Comment by p00f** [comment]
I've changed the readme, can you try again?

**Comment by robusta301** [comment]
I have a same problem with this output
![2021-04-30_23-51-44](https://user-images.githubusercontent.com/83468113/116727881-59a2b980-aa0f-11eb-9650-7c6f576b634b.png)

**Comment by p00f** [comment]
Okay your neovim uses lua 5.2, uninstall the old rock
`sudo luarocks uninstall http --lua-version 5.1`
then install the correct version
`sudo luarocks install http --lua-version 5.2`

**Comment by p00f** [comment]
Assuming 5.1 was a wrong assumption, I'll change the readme again tomorrow

**Comment by robusta301** [comment]
I managed to run :CphReceive and Parse Task in the browser, it run but nothing happens

**Comment by p00f** [comment]
Ok, run `:debug CphReceive` then type `cont` (as instructed) and press enter. Then parse task in browser

**Comment by p00f** [comment]
As an example, here is the expected behaviour without `:debug`


https://user-images.githubusercontent.com/36493671/116740458-af2c9580-aa12-11eb-922a-09098402f055.mp4

And here's the expected output with `:debug` (yours might be different because there's something wrong)


https://user-images.githubusercontent.com/36493671/116740610-e26f2480-aa12-11eb-920b-d5e68d9ba6cb.mp4

**Comment by p00f** [comment]
You don't have to run `:CphReceive` in an empty cpp file, you can run it on neovim's start screen too (in both cases it will create the contest solution file in its own directory and open that file

**Comment by p00f** [comment]
I've changed the readme again, @laniakeaaa @robusta301 can you try uninstalling the rock and installing as mentioned in the README?

**Comment by Juantamayo26** [comment]
This version work? Or is just 2.0.5?
![image](https://user-images.githubusercontent.com/47239906/117423220-1ac8a400-aee6-11eb-992e-598b814f8668.png)

**Comment by p00f** [comment]
> This version work? Or is just 2.0.5?
> ![image](https://user-images.githubusercontent.com/47239906/117423220-1ac8a400-aee6-11eb-992e-598b814f8668.png)
> 

Yes, use `--lua-version 5.1`

**Comment by p00f** [comment]
I've added a demo video to the README

**Comment by p00f** [comment]
> I've added a demo video to the README

Does it work for you guys @laniakeaaa @robusta301

**Comment by p00f** [comment]
Closing (no response from issue author)
